### ISSUE TITLE
Aumentar tamanho de campo de tradução e diminuir número de colunas

### ISSUE THREAD

**Issue by mbudzisch** [Mosquito13/busca-termos#7]
Não tem como diminuir o número de colunas de tradução, para deixar o campo maior e dar de ler a tradução melhor?

Isos iria facilitar muito a nossa vida:

![image](https://user-images.githubusercontent.com/98417723/151033794-f0965680-d4bb-4e9b-bbe9-a6ae65ce7cea.png)

**Comment by Mosquito13** [comment]
* Criar opção para quantidade de colunas nas traduções (1, 2 ou 3).
* Adicionar altura mínima para a tabela, caso o painel de traduções dê overflow,  adicionar rolagem.

**Comment by Mosquito13** [comment]
Done.
